//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STARSOST.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTQCRadarReport
    {
        public int RadarReportID { get; set; }
        public string Radar { get; set; }
        public int SamplingInterval { get; set; }
        public int CalculatedScans { get; set; }
        public int ReinforcementRate { get; set; }
        public int Mode3AValidity { get; set; }
        public int ModeCValidity { get; set; }
        public int SearchRTQCReliability { get; set; }
        public int BeaconRTQCReliability { get; set; }
        public int ZeroCode { get; set; }
        public int SearchBlipScan { get; set; }
        public int BeaconBlipScan { get; set; }
        public int RangeSplit { get; set; }
        public int RTQCReportReportID { get; set; }
    
        public virtual RTQCReport RTQCReport { get; set; }
    }
}
