//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STARSOST.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STARSdbEntity : DbContext
    {
        public STARSdbEntity()
            : base("name=STARSdbEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ParrotPEReportMessage> ParrotPEReportMessages { get; set; }
        public virtual DbSet<ParrotPEReport> ParrotPEReports { get; set; }
        public virtual DbSet<RadarRegistrationReport> RadarRegistrationReports { get; set; }
        public virtual DbSet<RadarSummaryReport> RadarSummaryReports { get; set; }
        public virtual DbSet<RegistrationReport> RegistrationReports { get; set; }
        public virtual DbSet<RTQCRadarReport> RTQCRadarReports { get; set; }
        public virtual DbSet<RTQCReport> RTQCReports { get; set; }
        public virtual DbSet<SystemEventMessaage> SystemEventMessaages { get; set; }
        public virtual DbSet<SystemMessageDictionary> SystemMessageDictionaries { get; set; }
        public virtual DbSet<TargetSummaryReport> TargetSummaryReports { get; set; }
    }
}
